version: '3.8'

networks:
  app-translator-network:
    name: app-translator-network
    driver: bridge

services:

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    networks:
      - app-translator-network
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    environment:
 
      - DATABASE_URL=postgres://user:password@db:5432/app_db

      - TRANSLATOR_URL=http://translator:5000/translate
    ports:
      - "3001:3001"
    networks:
      - app-translator-network
    depends_on:
      - db
      - translator

  translator:
    image: libretranslate/libretranslate
    environment:
      - LT_SUPPRESS_KEY_WARNING=True
      - LT_SSL_VERIFY=false
    ports:
      - "5000:5000"
    depends_on:
      - db  
    # networks:
    #   - app-translator-network

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: translations
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - app-translator_app-db-data:/var/lib/postgresql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-translator-network

volumes:
  app-db-data: